version: "3.7"

services:
        redis:
              image: redis:6.2-buster
              user: "1000:1000"
              command: redis-server --requirepass moneyprintergobrrr
              restart: on-failure
              stop_grace_period: 1m
              init: true
              volumes:
                  - ${APP_DATA_DIR}/redis:/data
              networks:
                  default:
                      ipv4_address: $APP_LNDHUB_REDIS_IP
        web:
                image: bluewalletorganization/lndhub:v1.3.0
                user: "1000:1000"
                depends_on: [ redis ]
                restart: on-failure
                stop_grace_period: 1m
                init: true
                ports:
                    - "${APP_LNDHUB_PORT}:${APP_LNDHUB_PORT}"
                volumes:
                        - ${LND_DATA_DIR}:/lnd:ro
                environment:
                    PORT: "${APP_LNDHUB_PORT}"
                    TOR_URL: "$APP_HIDDEN_SERVICE"
                    LND_CERT_FILE: "/lnd/tls.cert"
                    LND_ADMIN_MACAROON_FILE: "/lnd/data/chain/bitcoin/${BITCOIN_NETWORK}/admin.macaroon"
                    CONFIG: '{ "redis": { "port": 6379, "host": "$APP_LNDHUB_REDIS_IP", "family": 4, "password": "moneyprintergobrrr", "db": 0 }, "lnd": { "url": "$LND_IP:$LND_GRPC_PORT", "password": ""}}'
                networks:
                     default:
                        ipv4_address: $APP_LNDHUB_IP
