version: "3.7"

services:
  web:
    image: lncm/specter-desktop:v1.4.0@sha256:a54181fb1c849cb40116600f2061a58b5ccde9cb48c210b20f43178d76fce491
    stop_signal: SIGINT
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_SPECTER_DESKTOP_PORT:$APP_SPECTER_DESKTOP_PORT"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --host=0.0.0.0
      - --specter-data-folder=/data
    environment:
      BTC_RPC_USER: $BITCOIN_RPC_USER
      BTC_RPC_PASSWORD: $BITCOIN_RPC_PASS
      BTC_RPC_HOST: $BITCOIN_IP
      BTC_RPC_PORT: $BITCOIN_RPC_PORT
      BTC_RPC_PROTOCOL: http
    networks:
      default:
        ipv4_address: $APP_SPECTER_DESKTOP_IP
