version: "3.7"

x-logging:
  &default-logging
  driver: journald
  options:
    tag: "umbrel-app {{.Name}}"

services:
  web:
    image: lncm/specter-desktop:v1.3.1@sha256:c72fc1f270d6e5f8426f185e5c08fb8581728ad5c6ec943d719a9d08ce996c15
    stop_signal: SIGINT
    logging: *default-logging
    restart: on-failure
    stop_grace_period: 1m
    ports:
      - "$APP_SPECTER_DESKTOP_PORT:$APP_SPECTER_DESKTOP_PORT"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    command:
      - --host=0.0.0.0
      - --specter-data-folder=/data
    environment:
      BTC_RPC_USER: $BITCOIN_RPC_USER
      BTC_RPC_PASSWORD: $BITCOIN_RPC_PASS
      BTC_RPC_HOST: $BITCOIN_IP
      BTC_RPC_PORT: $BITCOIN_RPC_PORT
      BTC_RPC_PROTOCOL: http
    networks:
      default:
        ipv4_address: $APP_SPECTER_DESKTOP_IP
