version: 0

meta:
    category: "Wallet Servers"
    name: "Samourai Server"
    version: 1.9.0
    tagline: "Your private backing server for Samourai Wallet"
    description: |
        Samourai Server is an exclusive Umbrel app that runs Samourai Dojo and Whirlpool backing servers, and provides you easy step-by-step instructions to connect your Samourai Wallet to them. Samourai Wallet is unrivaled in transaction privacy, but its default configuration is still subject to network level privacy loss.

        By default, Samourai Wallet will connect to its centrally controlled Dojo hosted in Iceland. By hosting your own Samourai Server, you can bypass its servers completely when using Samourai Wallet or Sentinel, and gain total financial sovereignty without any complexity.
    developer: Samourai
    website: https://samouraiwallet.com
    dependencies:
    - "bitcoind"
    repo: "https://github.com/louneskmt/umbrel-samourai-dojo/tree/v1.9.0-umbrel"
    support: "https://t.me/SamouraiWallet"
    port: 3005
    path: "/connect/"
